version: '3.8'
name: support-bot
services:

  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine # the bleeding edge with all the fixes (and bugs)
    ports:
      - "8123:8123"
    ulimits:
      nofile: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DATABASE=default
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

volumes:
  clickhouse-data:
  clickhouse-logs:


